version: '3.5'
services:
  sensor1:
    image: jorgevargasjvm/practica-jms-sensors
    depends_on:
      - webbroker
    networks:
      - practica-jms
    
  sensor2:
    image: jorgevargasjvm/practica-jms-sensors
    depends_on:
      - webbroker
    networks:
      - practica-jms
      
  webbroker:
    image: jorgevargasjvm/practica-jms-web
    ports:
      - 80:8080
      - 61616:61616
    networks:
      - practica-jms
      
networks:
  practica-jms: